### ISSUE TITLE
Rotation sign

### ISSUE THREAD

**Issue by rspezialetti** [qq456cvb/PRIN#2]
https://github.com/qq456cvb/PRIN/blob/6657af740e514261e219d6b3990b69bf4fc9b0e0/dataset.py#L24
According to http://www.ece.montana.edu/seniordesign/archive/SP14/UnderwaterNavigation/Euler%20Angles.html should be     

def y(a):  return np.array([[np.cos(a), 0, -np.sin(a), 0],
                         [0, 1, 0, 0],
                         [np.sin(a), 0, np.cos(a), 0],
                         [0, 0, 0, 1]])

**Comment by qq456cvb** [comment]
Yes, you're right. If we define the rotation so that it's counterclockwise when the axis about which they occur points toward the observer, it should be what you said. I will correct it. Anyway, this has no effect on the results since random rotations by clockwise or counter-closewise are exactly the same.

**Comment by rspezialetti** [comment]
Thanks, i'll close the issue.
