### ISSUE TITLE
Questions about signal reconstruction.

### ISSUE THREAD

**Issue by SinestroEdmonce** [qq456cvb/PRIN#3]
Sorry to bother you. 
I am so unfamiliar with signal reconstruction. When I saw this line in your paper: ``every point will lie in some voxel but will not exactly lie in the voxel center. Thus we need to reconstruct the signal on S2 × H using sampled points.``, I was wondering why we need to reconstruct the signal when the points would not exactly lie in the voxel center.

**Comment by qq456cvb** [comment]
Like 2D image having pixels as its unit of resolution, 3D voxel also has a unit of resolution since we can only compute discrete convolutions by program. Therefore, one either sample points into regular grids or interpolate filters defined in regular grids at points' locations. The latter would bring a massive computing burden thus we choose the former one. By the way, we will update a version of our paper in a few days and explain our method more clearly. Stay tuned.
